---
# common variables for all

ansible_connection: local
ansible_become: yes
ansible_become_method: sudo

# dns_server & dns_search_suffix can both contain multiple values, separated by comma
dns_server: '192.168.2.1,192.168.1.1'
dns_search_suffix: 'int.layer8sys.com'
