---
    
- name: 'Install Docker'
  ansible.builtin.apt:
    name: docker.io
    state: present
#    pkg:
#    - docker-ce 
#    - docker-ce-cli 
#    - containerd.io 
#    - docker-buildx-plugin 
#    - docker-compose-plugin
